# File: .github/workflows/repo-sync.yml
name: 同步上游仓库
on:
  workflow_dispatch:
  schedule:
    - cron: '18 */2 * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 同步上游仓库
        uses: repo-sync/github-sync@v2
        with:
         # 替换成需要同步的用户名，仓库名，分支名。
          source_repo: ""
          source_branch: "main"
          destination_branch: "main"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}